### ISSUE TITLE
Make website mobile-friendly

### ISSUE THREAD

**Issue by obahareth** [obahareth/awesome-mena-conferences-and-meetups#12]
The website doesn't look too good on mobiles at the moment.

**Comment by lumie31** [comment]
Viewed this on chrome's mobile simulators and it didn't seem off. What exactly needs to be done?

**Comment by obahareth** [comment]
![98ab0fe1-50d7-4bfb-9694-04e5fe66f10d](https://user-images.githubusercontent.com/3428118/46913238-248a0500-cf92-11e8-9573-36321a3ae2cf.jpeg)

The content could fill more of the screen’s width, it’s a bit too “squished”.

**Comment by cdes** [comment]
I take this

**Comment by lumie31** [comment]
@cdes I wanted to, but you can have it
