### ISSUE TITLE
Setup testing environment and functionality

### ISSUE THREAD

**Issue by obahareth** [obahareth/awesome-mena-conferences-and-meetups#4]
Setup TravisCI to do the following:

- Ensure each conference/meetup has both an Arabic and English entry (`unique_identifier` could be used for this).
- Ensure that every website link is accessible (e.g. fetching it returns 200 OK).
- Ensure that every Twitter link is accessible (e.g. fetching it returns 200 OK).

This should use Node.js, I'm leaning more towards Jest and maybe Mocha.

**Comment by EhsanZ** [comment]
I think it would be better to re-title this issue to `Setup testing environment and test functionality`.
