### ISSUE TITLE
Prettify website

### ISSUE THREAD

**Issue by obahareth** [obahareth/awesome-mena-conferences-and-meetups#7]
**This is blocked by #6.**

I'm not that great with CSS, but I was thinking of just having two tabs in the main page, "Conferences" and "Meetups", where the default one is "Conferences" and they both just display all conferences and meetups for now (no need for any kind of pagination).

This might be a bit difficult with how I designed the conferences and meetups because they're Gatsby pages and I'm not sure if those are meant to be embeddable, perhaps they should be put into components, but I think we'd need to run the GraphQL queries differently then (perhaps StaticQuery?).

**Comment by burrelle** [comment]
I'll take a look at this!
